### ISSUE TITLE
Destination view slow response

### ISSUE THREAD

**Issue by katiecs3** [woodfields-warriors/ticket-to-ride#8]
Something is making the destination view not respond immediately on the client side. This could be due to running in an emulator, multiple calls to peek destination cards, or something else...

Related bugs in TA repository:
[Issue #156](https://github.com/byucs340ta/Fall2018/issues/156#issue-384980243)
[Issue #157](https://github.com/byucs340ta/Fall2018/issues/157#issue-384980769)

**Comment by katiecs3** [comment]
Update: I've been trying to get into the end game state, and it looks like every time I take a turn I get 40+ changes to the player stats object. So somewhere in the server y'all are sending over 40+ responses whenever the player object changes. This probably has a lot to do with how slow everything is.

**Comment by cameronconradt** [comment]
Missing bracket caused massive slowdown, fixed now
